Repository cloudquery/cq-provider-sdk, pull requests merged in 2022-02, with the labels that each got.

#173 fix: More DSN redactions
  database/dsn/dsn.go
  database/dsn/dsn_test.go
Labels: fix

#174 feat: Diagnostic squashing
  provider/diag/diagnostic.go
  provider/diag/diagnostics.go
  provider/diag/diagnostics_test.go
  provider/diag/error.go
  provider/diag/flat.go
  provider/diag/squash.go
  provider/execution/execution.go
  provider/execution/execution_test.go
  provider/provider_test.go
Labels: feat

#175 feat: Redacted diagnostics
  cqproto/grpc.go
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin.proto
  cqproto/internal/plugin_grpc.pb.go
  provider/diag/redacted.go
Labels: feat

#177 fix: Call resolve handler on ignore
  provider/execution/execution.go
Labels: fix

#176 feat: Add Support For Low level Copy
  database/postgres/pgdatabase.go
  provider/execution/mocks_test.go
  provider/execution/storage.go
  provider/execution/storage_test.go
  provider/schema/mock/mock_storage.go
Labels: feat

#178 fix: Remove subtests from RunMigrationsTest to avoid races
  migration/testbuilder.go
Labels: fix

#179 feat: Check if migrations are missing
  migration/migration.go
  migration/testbuilder.go
Labels: feat

#180 fix: Better counting of squashed diagnostics
  provider/diag/diagnostics.go
  provider/diag/diagnostics_test.go
  provider/diag/squash.go
Labels: fix

#181 feat: Testbuilder method with DSN and fresh DB
  migration/migrator/migrator.go
  migration/testbuilder.go
  provider/testing/resource.go
Labels: feat

#182 fix: Don't multiplexresolve if not needed
  provider/execution/execution.go
  provider/execution/execution_test.go
Labels: fix

#183 fix: Add filename format check to migrator
  migration/migrator/migrator.go
  migration/testbuilder.go
Labels: fix

#184 feat: Add max_goroutines
  cqproto/grpc.go
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin.proto
  cqproto/provider.go
  go.mod
  go.sum
  helpers/integers.go
  helpers/limits.go
  provider/execution/execution.go
  provider/execution/execution_test.go
  provider/provider.go
Labels: feat

#172 feat: Fetch status strings representation added
  cqproto/provider.go
Labels: feat

#186 fix: Convert go-migrate error to something readable
  migration/migrator/migrator.go
  migration/migrator/migrator_test.go
Labels: fix

#191 docs: Remove reference to Graph
  README.md
Labels: docs

#192 test: Fix test failures when local postgres instance has a different table schema
  provider/testing/resource.go
Labels: test

#190 fix: Clean up tablecreator, remove enable_partial_fetch in config template
  migration/table.go
  provider/provider.go
  provider/testing/resource.go
Labels: fix

#193 fix: Handle Less than 1 gb of memory
  helpers/limits.go
  helpers/limits_test.go
Labels: fix

#195 feat: Testing: Require cq_fetch_date on every tsdb table
  migration/testbuilder.go
Labels: feat
