Repository cloudquery/cq-provider-sdk, pull requests merged in 2022-04, with the labels that each got.

#218 fix: Fix nil fields testing
  .github/workflows/lint_golang.yml
  provider/testing/resource.go
Labels: fix

#220 fix: Count diag.PANIC as error
  provider/diag/diagnostics.go
  provider/execution/execution.go
Labels: fix

#222 feat: Ignore Table Completely in test
  provider/testing/resource.go
Labels: feat

#224 fix: Count panics as error in diags.Errors()
  provider/diag/diagnostics.go
Labels: fix

#221 feat: Testing. More ways to verify table content.
  provider/testing/resource.go
  provider/testing/verifiers.go
Labels: feat

#225 docs: Comments for IgnoreInTests
  provider/schema/column.go
  provider/schema/table.go
Labels: docs

#226 feat: ConfigureProvider to return diagnostics, add diag.USER and UnsquashDiag
  cqproto/grpc.go
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin.proto
  cqproto/provider.go
  provider/diag/diagnostic.go
  provider/diag/diagnostics.go
  provider/diag/error.go
  provider/diag/flat.go
  provider/diag/native.go
  provider/diag/squash.go
  provider/provider.go
  provider/provider_test.go
Labels: feat

#231 chore: Update Configure-not-called message
  provider/provider.go
Labels: ignore-for-release

#230 chore: More dsn test
  database/dsn/dsn_test.go
Labels: ignore-for-release

#232 fix: Testing: Handle Configure diags in providertest fetch
  provider/testing/resource.go
Labels: fix

#234 fix: Modulefiles on Windows
  provider/module/module.go
Labels: fix
