Repository cloudquery/cq-provider-sdk, pull requests merged in 2022-03, with the labels that each got.

#196 fix: Single insert
  database/postgres/pgdatabase.go
  provider/execution/execution.go
Labels: fix

#197 feat: Add migrator prehook
  migration/migrator/migrator.go
  migration/migrator/migrator_test.go
  migration/testbuilder.go
Labels: feat

#198 fix: Diagnostics should always include error message
  provider/diag/diagnostics_test.go
  provider/diag/error.go
  provider/execution/execution.go
  provider/execution/execution_test.go
  provider/provider_test.go
Labels: fix

#194 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
Labels: ignore-for-release

#199 fix: Diagnostics sorting, builtin Redacted() method
  provider/diag/diagnostics.go
  provider/diag/diagnostics_test.go
Labels: fix

#200 feat: Separate metadata per fetch request
  cqproto/grpc.go
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin.proto
  cqproto/provider.go
  provider/execution/execution.go
  provider/execution/execution_test.go
  provider/provider.go
  provider/schema/meta.go
  provider/schema/resource.go
Labels: feat

#201 feat: Tool: Handle PK changes on migrations
  migration/cli.go
  migration/table.go
  migration/testbuilder.go
Labels: feat

#202 feat: Add WrapError to add stacktrace
  provider/diag/error.go
  provider/execution/execution_test.go
  provider/testing/resource.go
Labels: feat

#204 fix: Tool: Add param to run in TSDB mode without TSDB
  migration/cli.go
  migration/migration.go
  migration/table.go
  migration/testbuilder.go
Labels: fix

#207 fix: Multiplex deadlock
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin_grpc.pb.go
  provider/execution/execution.go
Labels: fix

#205 fix: Extend IPAddressesResolver to support *[]string
  helpers/strings.go
  helpers/strings_test.go
  provider/schema/resolvers.go
Labels: fix

#208 fix: Multiplex deadlock fix
  provider/execution/execution.go
Labels: fix

#209 feat: Fetch timeout
  cqproto/grpc.go
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin.proto
  cqproto/internal/plugin_grpc.pb.go
  cqproto/provider.go
  provider/execution/execution.go
  provider/execution/execution_test.go
  provider/provider.go
Labels: feat

#211 fix: IgnoreErrors were showing as warn and errors
  .gitignore
  provider/execution/execution.go
  provider/execution/execution_test.go
  provider/provider_test.go
Labels: fix

#212 fix: Reintroduce ignored diags, handle correctly
  provider/execution/execution.go
  provider/execution/execution_test.go
  provider/provider_test.go
Labels: fix

#213 fix: Resolve column diags not returned
  provider/diag/error.go
  provider/execution/execution.go
Labels: fix

#214 fix: Clean up reattach file reading
  serve/reattach.go
Labels: fix

#216 chore: Sync form .github
  .github/workflows/issue_to_project.yml
Labels: ignore-for-release

#215 fix: Diagnostic counts
  provider/diag/diagnostics.go
Labels: fix

#217 feat: Test migration file structure
  migration/testbuilder.go
  migration/testbuilder_test.go
Labels: feat
