Repository cloudquery/cq-provider-sdk, pull requests merged in 2022-05, with the labels that each got.

#235 feat: Improved execution logging
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin_grpc.pb.go
  provider/execution/execution.go
  provider/execution/execution_test.go
  provider/provider.go
  provider/schema/meta.go
Labels: feat

#243 fix: Diag detail
  provider/diag/error.go
Labels: fix

#242 fix: Int64 to int automatic conversion added
  provider/schema/column.go
  provider/schema/dialect.go
  provider/schema/dialect_test.go
Labels: fix

#248 fix: Added json marshaling for []*struct -> json
  provider/schema/column.go
Labels: fix

#252 fix(deps): Update hashstructure
  go.mod
  go.sum
  provider/schema/resource.go
Labels: fix, automerge

#255 fix: Race condition
  provider/execution/execution.go
Labels: fix

#256 fix: Calculate goroutines with ulimit
  helpers/limit/limits.go
  helpers/limit/limits_test.go
  helpers/limit/ulimit_unix.go
  helpers/limit/ulimit_win.go
  helpers/limits.go
  provider/execution/execution_test.go
  provider/provider.go
Labels: fix

#258 fix: Use hashing FormatV1
  provider/schema/resource.go
Labels: automerge

#260 fix: Revert "fix(deps): Update hashstructure (#252)"
  go.mod
  go.sum
  provider/schema/resource.go
Labels: fix, automerge

#264 chore(style): Fix gocritic issues
  provider/execution/mocks_test.go
  provider/execution/storage_test.go
  provider/schema/meta_test.go
Labels: ignore-for-release, automerge

#265 fix: Executor fixes
  provider/execution/execution.go
  provider/schema/meta.go
Labels: fix

#266 fix: Delete by cq_id before insertion
  database/postgres/pgdatabase.go
  provider/execution/execution.go
  provider/execution/mocks_test.go
  provider/execution/storage.go
  provider/execution/storage_test.go
  provider/schema/mock/mock_storage.go
Labels: fix

#262 feat!: Migrations removal
  cqproto/grpc.go
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin.proto
  cqproto/internal/plugin_grpc.pb.go
  cqproto/provider.go
  database/postgres/pgdatabase.go
  migration/cli.go
  migration/longestcommon/lc.go
  migration/longestcommon/lc_test.go
  migration/migration.go
  migration/migrator/migrator.go
  migration/table.go
  migration/testbuilder.go
  migration/testbuilder_test.go
  provider/execution/mocks_test.go
  provider/execution/storage.go
  provider/execution/storage_test.go
  provider/provider.go
  provider/schema/column.go
  provider/schema/mock/mock_storage.go
  provider/schema/table.go
  provider/schema/table_test.go
  provider/testing/resource.go
Labels: feat, breaking

#285 fix: Upgrade cqproto protocol to v5
  cqproto/plugin.go
  serve/serve.go
Labels: fix

#283 fix(testing): Don't add ignored diagnostics to errors validation
  provider/testing/resource.go
Labels: fix, automerge

#288 feat: Implement Diagnostics.BySeverity filtering
  provider/diag/diagnostics.go
  provider/diag/diagnostics_test.go
Labels: feat

#284 chore: Fix style issues
  .github/workflows/lint_golang.yml
  .golangci.yml
  cqproto/grpc.go
  cqproto/plugin.go
  cqproto/provider.go
  database/dsn/dsn.go
  database/postgres/pgdatabase.go
  database/postgres/uuid.go
  helpers/limit/limits_test.go
  helpers/slice_test.go
  logging/logging.go
  migration/migrator/migrator.go
  migration/migrator/migrator_test.go
  migration/table.go
  provider/diag/diagnostic.go
  provider/diag/diagnostics.go
  provider/diag/diagnostics_test.go
  provider/diag/error.go
  provider/diag/native.go
  provider/diag/redacted.go
  provider/diag/squash.go
  provider/execution/execution.go
  provider/execution/execution_test.go
  provider/execution/mocks_test.go
  provider/execution/storage_test.go
  provider/provider.go
  provider/provider_test.go
  provider/schema/column.go
  provider/schema/column_test.go
  provider/schema/dialect.go
  provider/schema/filters.go
  provider/schema/filters_test.go
  provider/schema/meta.go
  provider/schema/resolvers.go
  provider/schema/resolvers_test.go
  provider/schema/resources_test.go
  provider/schema/table.go
  provider/schema/validators.go
  provider/schema/validators_test.go
  provider/testing/resource.go
  serve/serve.go
  testlog/testlog.go
Labels: ignore-for-release, automerge

#290 feat: Sortable flatdiags
  provider/diag/diagnostics.go
  provider/diag/diagnostics_test.go
  provider/diag/flat.go
Labels: feat

#237 feat(stats): Add heartbeat
  go.mod
  go.sum
  provider/execution/execution.go
  serve/debug.go
  serve/serve.go
  stats/stats.go
  stats/stats_test.go
Labels: feat, automerge

#293 fix(deps): Update hashstructure
  go.mod
  go.sum
  provider/schema/resource.go
Labels: fix, automerge

#295 fix: Null cq_id error
  provider/execution/execution.go
  provider/execution/execution_test.go
Labels: fix

#301 feat: Return full rlimit
  helpers/limit/limits.go
  helpers/limit/ulimit_unix.go
  helpers/limit/ulimit_win.go
Labels: feat, automerge
