Repository cloudquery/cq-provider-sdk, pull requests merged in 2022-01, with the labels that each got.

#147 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/add_tags.yml
  .github/workflows/golang_lint.yml
  .github/workflows/pr_title.yml
Labels: chore

#148 fix: Remove disable data delete option
  cqproto/grpc.go
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin.proto
  cqproto/provider.go
  provider/provider.go
  provider/provider_test.go
  provider/schema/execution.go
  provider/schema/execution_test.go
  provider/schema/resources_test.go
  provider/testing/resource.go
Labels: fix

#150 fix: Redact DSN parse errors
  database/dsn/dsn.go
  database/postgres/connection.go
Labels: fix

#149 chore: Synced file(s) with cloudquery/.github
  .github/workflows/add_tags.yml
Labels: ignore-for-release

#153 fix: Add test for dsn.RedactParseError
  database/dsn/dsn_test.go
Labels: fix

#156 feat: Support global tables
  database/postgres/pgdatabase.go
  go.mod
  go.sum
  provider/schema/table.go
Labels: feat

#155 fix: Fallback to initial version if requested version is lower than all we have
  migration/migrator/migrator.go
  migration/migrator/migrator_test.go
Labels: fix

#157 fix: Migrator should consider dialect columns
  migration/table.go
  provider/schema/column.go
Labels: fix

#158 fix: Allow reconfiguring provider in unmanaged mode
  provider/provider.go
  serve/serve.go
Labels: fix

#161 fix: Resolve count
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin_grpc.pb.go
  provider/schema/execution.go
Labels: fix

#163 fix: Sub-resource partial fetch error handling
  provider/provider.go
  provider/schema/execution.go
Labels: fix

#162 fix: Resource keys in resolve columns
  provider/schema/execution.go
  provider/schema/resource.go
  provider/schema/resources_test.go
Labels: fix

#168 test: Refactor TestResource function
  .gitignore
  provider/testing/resource.go
Labels: test

#170 chore: Synced file(s) with cloudquery/.github
  .github/workflows/lint_golang.yml
Labels: ignore-for-release

#167 feat: Added string representation of fetch status
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin.proto
  cqproto/provider.go
Labels: feat

#171 feat: Added string representation of fetch status
  cqproto/internal/plugin.pb.go
  cqproto/internal/plugin.proto
  cqproto/provider.go
Labels: feat
